config/routes.rb
Gamification::Application.routes.draw do
  resources :players
  resources :points
  resources :achievements do
    resources :points
  end

  root :to => 'visitors#new'
end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  has_one :point, inverse_of: :achievement, dependent: :destroy
  accepts_nested_attributes_for :point

  after_initialize do
    self.build_point unless self.point.present?
  end

  default_scope ->{ includes(:point) }
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :achievement, inverse_of: :point
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :set_achievement, only: [:show, :edit, :update, :destroy]

  # GET /achievements
  # GET /achievements.json
  def index
    @achievements = Achievement.all
  end

  # GET /achievements/1
  # GET /achievements/1.json
  def show
  end

  # GET /achievements/new
  def new
    @achievement = Achievement.new
  end

  # GET /achievements/1/edit
  def edit
  end

  # POST /achievements
  # POST /achievements.json
  def create
    @achievement = Achievement.new(achievement_params)


    respond_to do |format|
      if @achievement.save
        # cleanup, enqueue? (create a client somewhere else, and enqueue events)#
        client = Faye::Client.new('http://localhost:9292/faye')
        push = @achievement.attributes.merge(@achievement.point.attributes).to_json
        client.publish('/messages/achievement', push)


        format.html { redirect_to @achievement, notice: 'achievement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @achievement }
      else
        format.html { render action: 'new' }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /achievements/1
  # PATCH/PUT /achievements/1.json
  def update
    respond_to do |format|
      if @achievement.update(achievement_params)
        format.html { redirect_to @achievement, notice: 'achievement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /achievements/1
  # DELETE /achievements/1.json
  def destroy
    @achievement.destroy
    respond_to do |format|
      format.html { redirect_to achievements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_achievement
      @achievement = Achievement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def achievement_params
      params.require(:achievement).permit(:description, :title).merge(point_params)
    end

    def point_params
      params[:achievement].permit(point_attributes: [:value, :achievement_id, :value, :id, '_destroy'])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :total

  def total
    #TODO cache this.
    @total = Point.pluck(:value).reduce(:+)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params[:player]
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
    @achievement = Achievement.new
  end

end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/achievements/_form.html.erb
<%= form_for @achievement do |f| %>
  <%#= f.error_notification %>

  <div class="form-inputs">
    <%= f.text_field :title, placeholder: "Achievement" %>
    <%= f.text_field :description, placeholder: "Description" %>

    <%= f.fields_for :point do |p| %>
      <%= p.number_field :value, placeholder: "Value" %>
    <% end %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/achievements/edit.html.erb
<h1>Editing achievement</h1>

<%= render 'form' %>

<%= link_to 'Show', @achievement %> |
<%= link_to 'Back', achievements_path %>

app/views/achievements/index.html.erb
<h1>Listing achievements</h1>

<table>
  <thead>
    <tr>
      <th>title</th>
      <th>description</th>
      <th>point</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @achievements.each do |achievement| %>
      <tr>
        <td><%= achievement.title %></td>
        <td><%= achievement.description %></td>
        <td><%= achievement.point.value %></td>

        <td><%= link_to 'Show', achievement %></td>
        <td><%= link_to 'Edit', edit_achievement_path(achievement) %></td>
        <td><%= link_to 'Destroy', achievement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Achievement', new_achievement_path %>

app/views/achievements/new.html.erb
<h1>New achievement</h1>

<%= render 'form' %>

<%= link_to 'Back', achievements_path %>

app/views/achievements/show.html.erb
<p id="notice"><%= notice %></p>
<%= @achievement.title %>
<br>
<%= @achievement.description %>
<%= @achievement.point.value %>
<%= @achievement.point.id %>
<br>
<%= link_to 'Edit', edit_achievement_path(@achievement) %> |
<%= link_to 'Back', players_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'About', page_path('about') %></li>
</ul>
<div id='ticker' class="pull-right"><%= @total || 0 %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Bootstrap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application", "http://localhost:9292/faye/client.js" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

app/views/players/_form.html.erb
<%= simple_form_for(@player) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/visitors/new.html.erb
<h3>Home</h3>
  <ul id="feed">
  </ul>
<%= render 'achievements/form' %>